// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
/*



import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwzSv4NAxtc2vTTF5E2_BIFDMhC9kra_A',
    appId: '1:389126638247:web:bc1fd5a3e13195b73d2982',
    messagingSenderId: '389126638247',
    projectId: 'comercialmathiazapp',
    authDomain: 'comercialmathiazapp.firebaseapp.com',
    storageBucket: 'comercialmathiazapp.firebasestorage.app',
    measurementId: 'G-EG27S2D837',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAafInyi1r0Oeb26k7rK-0ilAYT2duoMjQ',
    appId: '1:389126638247:android:42e39a3d727cd5423d2982',
    messagingSenderId: '389126638247',
    projectId: 'comercialmathiazapp',
    storageBucket: 'comercialmathiazapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo7L6-ka-qSO-bpWLVqUIvXo2vrrd4qsk',
    appId: '1:389126638247:ios:f7788449f6b6034f3d2982',
    messagingSenderId: '389126638247',
    projectId: 'comercialmathiazapp',
    storageBucket: 'comercialmathiazapp.firebasestorage.app',
    iosBundleId: 'com.example.proyectoMathiaz',
  );
}
*/